### ISSUE TITLE
Mockingjay stub method overwriting Cuckoo stub method

### ISSUE THREAD

**Issue by benniebotha** [kylef/Mockingjay#100]
We are using a Swift mocking library called [Cuckoo](https://github.com/Brightify/Cuckoo) that allows for easier unit tests. The recent inclusion of Mockingjay has created a problem with all of the other tests using [Cuckoo](https://github.com/Brightify/Cuckoo) as [Cuckoo](https://github.com/Brightify/Cuckoo) defines a method called stub as well but in the global scope. The XCTest extension takes president in all of the tests and creates a compile time error. All of the [Cuckoo](https://github.com/Brightify/Cuckoo) stub methods could be replaced with Cuckoo.stub, but this is not an ideal solution as Mockingjay.stub would be much better as Mockingjay is used much less and would also not be necessary if the stub method was only defined in the file it was imported in, but swift extensions propagate everywhere.

What can be done to either rename the stub method or import only in one file? Any other suggestions would be great. Thanks in advance.

**Comment by kylef** [comment]
@benniebotha If you depend just on the core (excluding https://github.com/kylef/Mockingjay/blob/978253ce130410a677f132e87736c7a149bf5889/Mockingjay.podspec#L15). The stub method on XCTest won't exist, you can use `Mockingjay.addStub` instead (or create your own alias for it).

```swift
MockingjayProtocol.addStub(matcher: matcher, delay: delay, builder: builder)
```

https://github.com/kylef/Mockingjay/blob/978253ce130410a677f132e87736c7a149bf5889/Sources/Mockingjay/XCTest.swift

The XCTest also adds a tearDown hook to remove stubs so you want to implement similiar.

**Comment by benniebotha** [comment]
Thanks for the advice, that should work.
