### ISSUE TITLE
swift4.2 support

### ISSUE THREAD

**Issue by acumen1005** [kylef/Mockingjay#103]

**Comment by jblue200** [comment]
Any idea when the library will upgrade to support Swift 4.2? Thanks.

**Comment by SebastianView** [comment]
would be great to have Swift 4.2 support soon!

**Comment by MedAmineWinners** [comment]
I think that we should stop working with this library, there is no more interaction

**Comment by bishalg** [comment]
Last code commit was 2 years ago ! So do we have any other alternative framework ? 

> I think that we should stop working with this library, there is no more interaction
