### ISSUE TITLE
Pod Swift Version Is Not Specified

### ISSUE THREAD

**Issue by jakeholland** [kylef/Mockingjay#108]
The `spec.swift_version` is not specific in the `podspec`. This causes Cocoapods to use the project default which causes Swift 5 projects to fail building.

**Comment by kylef** [comment]
Can try [Mockingjay 3.0.0-alpha.1](https://github.com/kylef/Mockingjay/releases/tag/3.0.0-alpha.1):

```ruby
pod 'Mockingjay', '3.0.0-alpha.1'
```
