### ISSUE TITLE
URITemplate Broke

### ISSUE THREAD

**Issue by skorebrits** [kylef/Mockingjay#16]
Hi URITemplate is not yet compatible with swift 1.2. Can you link to the new version in pod spec when it comes out?

**Comment by kylef** [comment]
Certainly can. I don't have time to sort this out now, but I'll try find time later tonight or over the weekend.

If you'd like to help move this on, a pull request adding Swift 1.2 support would be greatly appreciated.

**Comment by skorebrits** [comment]
Thanks I made the fix for now in the pod. I just used the Xcode 6.3 error completion and everything run fine again. I'll have a look tomorrow to make a pull request and make the changes.
