### ISSUE TITLE
NSURLSessionConfiguration swizzling with Alamofire

### ISSUE THREAD

**Issue by nwest** [kylef/Mockingjay#22]
This is a strange one. Mockingjay's `initialize()` on `XCTest` is working as expected but the one on `NSURLSessionConfiguration` never actually fires. 

The swizzle hooks properly if you manually call `NSURLSessionConfiguration.initialize()`, otherwise `MockingjayProtocol` never gets pushed into `protocolClasses` in the configuration.

Xcode 7.0 (7A220)
Alamofire 2.0.0

[Here's the relevant code](https://github.com/Alamofire/Alamofire/blob/master/Source/Manager.swift#L36-L41) on Alamofire.

**Comment by nwest** [comment]
This turned out to be a project issue from a Xcode 6 generated project.

**Comment by kylef** [comment]
Glad you managed to figure it out @nwest, was digging into this.

**Comment by adamwaite** [comment]
I've just run into this too. Calling `NSURLSessionConfiguration.initialize()` fixes it. Is there a way I can fix it without having to do that? I don't actually understand the what the cause is? Thanks

**Comment by nwest** [comment]
I spent a few days trying to figure out what was causing this and couldn't pin it down. Generating a new pbxproj and migrating the files over didn't help.

I tried making a test project to reproduce this issue, and I couldn't.

Another thought: would ATS affect NSURLProtocol in some weird way?

**Comment by kylef** [comment]
I've never had this not work out of the box in all my test projects. Do any of you have some test dependencies that might affecting Mockingjay? Perhaps ones that perform swizzling.

ATS should not affect Mockingjay.

**Comment by nwest** [comment]
If two extensions implement the same method, how does Swift distinguish which is called? I don't think any of my other dependencies are doing this, but I also had the same thought. Implementing `NSURLSessionConfiguration.initialize()` in an extension on the main target does get called when Mockingjay's implementation does not. 

Here's my Podfile: https://gist.github.com/nwest/dc8f78d5d5be8bfc8dfe

I looked through these pods and tried to find them implementing that method, and found nothing. Also, adding these pods to my example project doesn't break Mockingjay :frowning:

**Comment by kylef** [comment]
I have a feeling that `fabric` might be causing this. The issue could be a loading order between fabric and Mockingjay. If the app delegate is setting up fabric then the fabric's framework will be loaded before Mockingjay is, and thus if they are also implementing `initialize` this may fail.

@nwest Would you be able to confirm this? (You should be able to comment out the usage of Fabric to confirm).

Once we know if that is the case, we can try and figure out a different approach.

**Comment by nwest** [comment]
Removing `Fabric.with([Crashlytics()])`, the Fabric keys run script, and `NSURLSessionConfiguration.initialize()` in the spec caused the tests to pass.

**Comment by kylef** [comment]
@nwest Could you test the kylef/swizzle-nrlsessionconfig-xctest branch and see if it solves your problem? Then I can make a release with that included.

**Comment by nwest** [comment]
```sh
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `Mockingjay` from `git@github.com:kylef/Mockingjay.git`, branch `swizzle-nrlsessionconfig-xctest`

[!] Error installing Mockingjay
[!] /usr/local/bin/git clone git@github.com:kylef/Mockingjay.git /var/folders/dn/kfjzqbb11h901dt34x8wbqbh0000gp/T/d20151012-20506-udeasg --single-branch --depth 1 --branch swizzle-nrlsessionconfig-xctest

Cloning into '/var/folders/dn/kfjzqbb11h901dt34x8wbqbh0000gp/T/d20151012-20506-udeasg'...
warning: Could not find remote branch swizzle-nrlsessionconfig-xctest to clone.
fatal: Remote branch swizzle-nrlsessionconfig-xctest not found in upstream origin
```

Yikes. Looking into this. https://github.com/CocoaPods/CocoaPods/issues/2494 ha!

**Comment by kylef** [comment]
@nwest I think you missed the `kylef` prefix on the branch name.

**Comment by nwest** [comment]
That was it, thanks. 

The patch on `kylef/swizzle-nrlsessionconfig-xctest` fixes the conflict with Fabric/Crashlytics.
