### ISSUE TITLE
Tag 1.0.0 Release

### ISSUE THREAD

**Issue by simonrice** [kylef/Mockingjay#23]
I'm sure you'll find this issue a doddle to fix!

I'm having trouble using v1.0.0 via CocoaPods because there's no 1.0.0 tag on this repository.

Just in case you need this, this is what `pod install` says:

```
[!] Error installing Mockingjay
[!] /usr/local/bin/git clone https://github.com/kylef/Mockingjay.git /var/folders/1f/j5dkbzz11wq7r6wpy0zl38t00000gn/T/d20150922-6859-12gu0sb --single-branch --depth 1 --branch 1.0.0

Cloning into '/var/folders/1f/j5dkbzz11wq7r6wpy0zl38t00000gn/T/d20150922-6859-12gu0sb'...
warning: Could not find remote branch 1.0.0 to clone.
fatal: Remote branch 1.0.0 not found in upstream origin
```

**Comment by adamwaite** [comment]
Yeah I'm getting this too. Can solve with `git: 'https://github.com/kylef/Mockingjay/'` for now.

**Comment by kylef** [comment]
Sorry about that, this has been fixed now, please try again.

**Comment by adamwaite** [comment]
Confirmed working, thanks.

**Comment by simonrice** [comment]
Cheers @kylef 😊 I can also confirm it's working!
