### ISSUE TITLE
jsonData in Pod release

### ISSUE THREAD

**Issue by adamwaite** [kylef/Mockingjay#25]
Hey Kyle,

Great work. Just wanted to point out that the jsonData builder isn't in the CocoaPod release, in case you didn't know.

Thanks

**Comment by istx25** [comment]
Any update on this?

**Comment by kylef** [comment]
Just released 1.1.0

**Comment by istx25** [comment]
@kylef We have `jsonData` but now we don't have `stub`. Not sure why.

**Comment by istx25** [comment]
or matcher
