### ISSUE TITLE
Sample code is also out of date because Swift 2.

### ISSUE THREAD

**Issue by istx25** [kylef/Mockingjay#27]
Sample code is also out of date because Swift 2.

**Comment by kylef** [comment]
Can you share any particular example that doesn't work?

They should all work in Swift 2.0.

**Comment by istx25** [comment]
For some reason `self.dynamicType` isn't being recognised in Xcode 7.0.1 (7A1001).

```swift
let path = NSBundle(forClass: self.dynamicType).pathForResource("fixture", ofType: "json")!
let data = NSData(contentsOfFile: path)!
stub(matcher, builder: jsonData(data))
```

**Comment by istx25** [comment]
May be related to #28. :grimacing:

**Comment by kylef** [comment]
That example is expecting from inside a function (`setUp`) where self is the instance of the function. You are using self inside a class method thus it isn't available.

I see you've already used the name bundle in your other example (#28) and figured this out.
