### ISSUE TITLE
Minimum deployment target 9.1 error Xcode 7.1

### ISSUE THREAD

**Issue by diogoguimaraes** [kylef/Mockingjay#33]
I've just upgraded my Xcode to 7.1 and I'm no longer being able to build Mockingjay due to the following error: `Module file's minimum deployment target is ios9.1 v9.1:`
Do you have any idea how to fix this?
Thanks.

**Comment by kylef** [comment]
Can you try deleting derived data and cleaning. I think this is an Xcode cache problem.

**Comment by diogoguimaraes** [comment]
Done as you said and it didn't fix the error.

**Comment by kylef** [comment]
How did you install Mockingjay? Can you share a larger portion of the build log.

**Comment by diogoguimaraes** [comment]
I installed using Carthage:
Cartfile
`github "kylef/Mockingjay" ~> 1.1.0`
Using the following command to checkout the project:
`carthage update --platform iOS --no-build`

Then I drag and drop the Mockingjay project from Carthage/Checkouts` to my project and set the dependency on Xcode. After the update to Xcode 7.1 it started to give that error on build.

I've also tried in another environment and the issue persists.

**Comment by diogoguimaraes** [comment]
Also, it is failing in when building in travis with the same error: `module file's minimum deployment target is ios9.1 v9.1:`

**Comment by kylef** [comment]
I can build and run Mockingjay fine on Xcode 7.1, and so can [Travis CI](https://travis-ci.org/kylef/Mockingjay/builds/88422392). Are you using Mockingjay from master? if not, please try that.

**Comment by diogoguimaraes** [comment]
I checked out mockingjay from master and it fixed the issue. When are you planning to have a new release of Mockingjay?
Thank you.

**Comment by diogoguimaraes** [comment]
@kylef any news on the ETA to the next release?

Thanks.

**Comment by paulyoung** [comment]
I'm seeing this also, I think the only thing I did differently was start using Xcode 7.1

**Comment by paulyoung** [comment]
It does sound suspiciously like this radar I filed: https://github.com/paulyoung/radars/tree/master/22816454

**Comment by paulyoung** [comment]
Just wanted to confirm that using 40a2f0f4efb483b398dfe46e5d8a3cf6c1510ec3 (`master` at the time of writing) works for me. :+1:
