### ISSUE TITLE
Getting Library not loaded

### ISSUE THREAD

**Issue by Tokuriku** [kylef/Mockingjay#35]
I'm getting the following error in the console but am at a miss to fix it.
Can someone help?

```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/Dev/Library/Developer/Xcode/DerivedData/test-hehyhfozbszkqvgifetexjhfsqsz/Build/Products/Debug-iphonesimulator/Mockingjay.framework/Mockingjay
  Reason: image not found
```

**Comment by kylef** [comment]
This would seem that XCTest is not available to your target. How did you integrate Mockingjay into your project?

**Comment by ogezue** [comment]
Same problem here. My podfile looks like this:

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

pod 'Alamofire', '~> 3.1.4'
pod 'AlamofireObjectMapper', '~> 2.1.0'
pod 'RealmSwift', '~> 0.97.0'
pod 'KeychainAccess', '~> 2.3.3'
pod 'Mattress', '~> 1.0.2'
pod 'ReachabilitySwift', '~> 2.3.3'
pod 'SwiftyBeaver', '~> 0.3'
pod 'Mockingjay', '~> 1.1.1'

link_with 'MyApp', 'MyAppTests'

**Comment by kylef** [comment]
@ogezue You probably don't want to be installing Mockingjay into you application, but only your tests. So the following Podfile (if you're running CocoaPods 1.x):

```ruby
platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'MyApp' do
  pod 'Alamofire', '~> 3.1.4'
  pod 'AlamofireObjectMapper', '~> 2.1.0'
  pod 'RealmSwift', '~> 0.97.0'
  pod 'KeychainAccess', '~> 2.3.3'
  pod 'Mattress', '~> 1.0.2'
  pod 'ReachabilitySwift', '~> 2.3.3'
  pod 'SwiftyBeaver', '~> 0.3'

  target 'MyAppTests' do
    pod 'Mockingjay', '~> 1.1.1'
  end
end
```

**Comment by ogezue** [comment]
Great! This solves it!

**Comment by kylef** [comment]
Perfect!
