### ISSUE TITLE
Using Mockingjay in app target (no XCTest)

### ISSUE THREAD

**Issue by alessandroorru** [kylef/Mockingjay#36]
I want to use Mockingjay in my app to stub real APIs while they are still in development, so I tried what @kylef suggested in #28, but it is not working because you also need to swizzle the NSURLSessionConfiguration (as the implementation in Mockingjay/XCTest does).

The final replacement `stub` method should be: 

```
func stub(matcher:Matcher, builder:Builder) -> Stub {
    NSURLSessionConfiguration.mockingjaySwizzleDefaultSessionConfiguration()    
    return MockingjayProtocol.addStub(matcher, builder: builder)
}
```

Since using Mockingjay without XCTest could be a useful scenario, maybe it is worth having a note in the readme, or even better supporting this natively.

Another issue is that using the full Mockingjay pod in a test target while using Mockingjay/Core pod in the app creates conflicts on compilation, since if you include both pods they will be compiled as a single framework, I guess (maybe Cocoapods error?).
In my opinion, the `stub` method should be moved to another global place (like Mockingjay.stub), so that it would be available regardless of XCTest, while the XCTest stuff should be moved to a separate framework or even removed entirely, since it is so simple (and much more clear) to just add a `removeAllStubs` on `tearDown` method in a test case, like OHHTTPStubs does.

**Comment by simonmcl** [comment]
+1 

Found the README to be fairly confusing / misleading around this. While it says it has `full XCTest integration`, it doesn't say that XCTest is required. Its quite a common use case to stub backend API's while in development, or debugging. It would be useful to have both options, and it needs to be spelled out clearer in the README.

**Comment by jakunico** [comment]
+1 on using stubs for development outside of tests targets

**Comment by kylef** [comment]
As of version 1.2.1, Mockingjay will swizzle NSURLSessionConfiguration on load so doing this manually is unnecessary.

As for running Mockingjay without XCTest, that is possible and XCTest is not required. If you integrate Mockingjay with CocoaPods by depending on `Mockingjay/Core`, XCTest will not be required. You can use the following APIs:

- `MockingjayProtocol.addStub(matcher, builder)`
- `MockingjayProtocol.removeStub(stub)`
- `MockingjayProtocol.removeAllStubs()`

**Comment by invalidname** [comment]
Sorry to drop in late on a closed issue, but is there anything special you need to do with your Podfile to make this work? I have my app's pod target doing `pod 'Mockingjay/Core'`, and my tests target doing `pod 'Mockingjay'`, and now running the tests crashes with `dyld: Symbol not found` on an `XCTest.stub()`.

Have only been fighting this for a couple hours, so maybe posting here is premature.

**Comment by kylef** [comment]
@invalidname Could you share a bit more of your Podfile please.

**Comment by invalidname** [comment]
Thanks @kylef. Hiding my company's stuff as `myproject`, it's something like:
```
def myproject_pods
    pod 'Fabric', '~> 1.6.11'
    pod 'Crashlytics', '~> 3.8.3'
   # etc
end

target 'myproject' do
    shared_pods
    myproject_pods

    pod 'Mockingjay/Core'
end
    
target 'myprojectTests' do
   inherit! :search_paths
        
    shared_pods
    myproject_pods
    shared_testPods
        
    pod 'Quick', ' ~> 0.9.2'
    pod 'Mockingjay'
    pod 'RxBlocking', '~> 2.6'
end
```

**Comment by kylef** [comment]
@invalidname I think you will want to try something more along the lines of:

```ruby
target 'MyProject' do
  pod 'Mockingjay/Core'
  # all pods that are not test go here

  target 'MyProjectTest' do
      inherit! :search_paths
      pod 'Mockingjay/XCTest'
      pod 'Quick', ' ~> 0.9.2'
      # .. all test pods go here
  end
end
```

**Comment by invalidname** [comment]
@kylef thanks, but still crashing.

**Comment by natan** [comment]
I also wanted to use Mockingjay in my main app target and it took some head scratching and searching to find this page. Probably worth adding this information to the README.
