### ISSUE TITLE
Problem using MockingJay

### ISSUE THREAD

**Issue by ogezue** [kylef/Mockingjay#39]
I have a model class that fetches data from my server using AlamoOnFire, ObjectMapper and Realm  for persistance. Realm introduces the List<Type> construct.

My problem is that MockingJay doesn't seem to be used. The JSON-File from the file-system can be loaded in my test and contains the data that is computed correctly if fetched from server.

Any idea what could be wrong?

```swift
import XCTest
import Mockingjay
import RealmSwift
@testable import MyApp

class OverviewModelTests: XCTestCase {

    override func setUp() {
        super.setUp()
        let path = NSBundle(forClass: self.dynamicType).pathForResource("Overview", ofType: "json")!
        let data = NSData(contentsOfFile: path)!
        stub(everything, builder: jsonData(data))
    }
    //http(.GET, uri: URLs.sharedInstance.overviewItemsUrl())


    func testFetchOverviewItems() {
        
        let overviewModel = OverviewModel()
        
        overviewModel.fetchOverviewItemList({ (itemList: List<OverviewItem>) -> () in
            
            XCTAssertTrue(itemList.count == 6)
            })
            { (error: ErrorType?) -> () in
                XCTFail("Error in testFetchOverviewItems ")
            }
    }


}
```

**Comment by paulyoung** [comment]
I'm seeing a similar thing with Xcode 7.2 and Swift 2.1.1 using the same technique as a different project that is known to work with Xcode 7.0 and Swift 2.0

I'll try to provide more details.

**Comment by paulyoung** [comment]
From what I can tell, differences in Xcode / Swift versions have no relevance to my issue.

I've tried stepping through in the debugger but my matcher is never called.

This is the relevant [spec](https://github.com/the-grid/Portal/blob/cce3a6cf9cf5418ad982ae7e35ad3dc9990a025c/PortalTests/Networking/Resources/User/GetUserSpec.swift) and [test failure](https://travis-ci.org/the-grid/Portal#L2180).

**Comment by paulyoung** [comment]
@kylef any tips on how to debug this?

**Comment by paulyoung** [comment]
I little bit more info – my `APIClient` accepts a `configuration` argument, so I created a configuration the same as [the one that Mockingly swizzles](https://github.com/kylef/Mockingjay/blob/2fa2d7002b4634a891ee31371162b558592e53f6/Mockingjay/NSURLSessionConfiguration.swift#L28-L29) and passed that in:

```swift
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
configuration.protocolClasses = [MockingjayProtocol.self] as [AnyClass] + configuration.protocolClasses!
                    
let token = "token"
let client = APIClient(token: token, configuration: configuration)
```

This produced the same test failure.

**Comment by paulyoung** [comment]
After setting a breakpoint in `canInitRequest:` on `MockingjayProtocol` I'm able to step through and see that my matcher _is_ called.

This now looks like an error on my part. Why I wasn't able to step through or pause execution on those breakpoints before, I'm not sure.

**Comment by paulyoung** [comment]
I fixed the issue on my side and the test passed, so I removed the manually passed `configuration` and can confirm that `canInitRequest:` is never called.

**Comment by paulyoung** [comment]
I can only assume that `method_exchangeImplementations(m1:m2:)` is not working as expected, since that line is executed but `mockingjayDefaultSessionConfiguration()` is never called.

**Comment by kylef** [comment]
Would you be able to check `protocolClasses` in `NSURLSessionConfiguration` inside `NSURLSession` returns an array of protocols with `MockingjayProtocol` being the first result?

This should only happen after the first `stub` was registered via `XCTestCase.stub`, I'm wondering if `NSURLSession` makes a copy of the protocols before this is registered.

If this isn't the case, perhaps you could try explicitly exchanging these methods by calling the following before anything related to NSURLSession happens:

```swift
NSURLSessionConfiguration.mockingjaySwizzleDefaultSessionConfiguration()
```

If this solves the problem, then we will need to revisit where this exchange is done within Mockingjay.

**Comment by paulyoung** [comment]
I'm planning on looking into this when I get chance.

**Comment by tamamachi** [comment]
I think I encountered the same problem when I updated Mockingjay form 1.1.0 to 1.1.1.
I'm using [Quick](https://github.com/Quick/Quick) and adding `NSURLSessionConfiguration.mockingjaySwizzleDefaultSessionConfiguration()`  to beforeSuite worked like a charm!
Thanks a lot.

**Comment by krodak** [comment]
@kylef I can confirm too that currently, method swizzling doesn't work.
I tried @paulyoung approach but to no avail.
Even if I put swizzling in AppDelegate it won't replace the default session.

**Comment by LukeJang** [comment]
I simply use `MockingjayProtocol.addStub(matcher: Matcher, builder: Builder)` instead off stub(matcher: Matcher, builder: Builder) for my test. It worked.

**Comment by IvanRublev** [comment]
Swizzling works for Xcode 7.2 and Swift 2.1.1. And stubbing goes well. 
Check the order in which stubbing (and as consequence swizzling)  and creation of `NSURLSession` instance occurs. 

For example, if you use the Alamofire and your tested target is calling `Alamofire.Manager.sharedInstance` somewhere on the app's start, then this `sharedInstance`'s underlying `NSURLSession` object's configuration __is not__ swizzeled with Mockingjay protocol. It's because the `sharedInstance` is initialized on Manager class load. And that occurs before your test starts and swizzling occurs.)

To workaround this you should redesign your app or test to use the custom `Manager` instance. If you make Mockingjay to swizzle before initializing the `Manager` instance:
```
NSURLSessionConfiguration.mockingjaySwizzleDefaultSessionConfiguration()
let requestManager = Manager(configuration: NSURLSessionConfiguration.defaultSessionConfiguration())
```
Then requests to the `requestManager` will be stubbed successfully.

**Comment by kylef** [comment]
I've made some changes in Mockingjay 1.2.1 which now swizzles NSURLSessionConfiguration on load of Mockingjay.

This fixes problems when you create a session and then register a stub before we've added the Mockingjay protocol to NSURLSessionConfiguration.

If anyone is still having any problems with Mockingjay after 1.2.1, please file a new issue with steps to reproduce the problem and I'll take a look.

Thanks all!
