### ISSUE TITLE
Preventing unintended network requests for unmatched requests

### ISSUE THREAD

**Issue by paulyoung** [kylef/Mockingjay#41]
In my current use of Mockingjay I find that if my implementation is somehow incorrect and the matcher returns `false`, actual network requests are made.

This is all working as expected, but I would prefer it if no networks requests were made, and any unintended requests cause a test to fail.

Is this somehow possible already? If not, I think something like an `everythingExcept` matcher could be useful.

**Comment by paulyoung** [comment]
I quickly realized that `everythingExcept` suggests mocking everything except some request.

I hope the intention is clear enough though.

**Comment by kylef** [comment]
This is possible, you can register an `everything` matcher before others. Remember that when matching, Mockingjay will look at the newest registered matchers first.

Here's an example:

```swift
override func setUp {
  super.setUp()

  // catch-all for un-matched requests
  let error = NSError(/* todo proper error */)
  stub(everything, failure(error))
}

func testX() {
  stub(http(.PUT, "/kylef/Mockingjay"), ...)
}
```

Does this make sense / solve your problem @paulyoung?

**Comment by paulyoung** [comment]
@kylef yes, that works really well! Thanks.

**Comment by paulyoung** [comment]
@kylef it turns out that I had a focused test when I tried this earlier.

After looking again it seems like I need to out the `everything` stub/matcher _after_ and not before.

Can you confirm?

**Comment by kylef** [comment]
Sorry, from memory that's how I though I implemented it. I've made it work this way in https://github.com/kylef/Mockingjay/commit/59ec169c9e537d8caae89fc67e776b00fabeafbf

Can you confirm if this works for you?

**Comment by paulyoung** [comment]
I'll try this out when I can.
