### ISSUE TITLE
anyone working on swift 2.2?

### ISSUE THREAD

**Issue by jonasman** [kylef/Mockingjay#45]

**Comment by rlester** [comment]
Looks like there is a merged pull request for 2.2 support. But with that said it also looks like the changes have not been applied to an updated cocoapods version yet.

https://github.com/kylef/Mockingjay/pull/44

**Comment by jonasman** [comment]
yeah we need cocoapods update

**Comment by kylef** [comment]
This has been released as 1.2.1.
