### ISSUE TITLE
Cannot stub a uri without complete url scheme

### ISSUE THREAD

**Issue by GUL-** [kylef/Mockingjay#47]
Using mockingjay to stub api calls that can be done on any baseUrl, I am doing this:
`self.stub(http(.PUT, uri: "/session/{session_id}/rate?user_id={user_id}"), builder: http(400))`

This does not work, I need to do this:
`self.stub(http(.PUT, uri: "http://demo.usievents.com/api/v1/session/42/rate?user_id=42"), builder: http(400))`

Digging into URITemplate.swift, it seems you add a "^" in front of the regex, thus it expects the matching to occurs on first character.

**Comment by kylef** [comment]
This is intended, you would need to include the complete path. You've missed out `/api/v1` from the path.

So it should be:

```
/api/v1/session/{session_id}/rate?user_id={user_id}
```

Instead of:

```
/session/{session_id}/rate?user_id={user_id}
```
