### ISSUE TITLE
Cannot stub Alamofire request in Mockingjay 1.2.1

### ISSUE THREAD

**Issue by RyogaK** [kylef/Mockingjay#51]
Mockingjay 1.2.1 not works for Alamofire.
btw, 1.1.1 works well.

**Comment by kylef** [comment]
Hi @RyogaK,

Would you be able to help me debug what's causing this problem.

Please can you check that `protocolClasses` in `NSURLSessionConfiguration` inside `NSURLSession` returns an array of protocols with `MockingjayProtocol` being the first result?

If this isn't the case, perhaps you could try explicitly exchanging these methods by calling the following before anything related to NSURLSession happens:

```swift
NSURLSessionConfiguration.mockingjaySwizzleDefaultSessionConfiguration()
```

**Comment by slhodson969** [comment]
I can also confirm this is happening. I just spent about 3 hours trying to work out why the stubs in our unit tests were no longer working.

I'm a little busy to dig into it at the moment so have just downgraded to `1.1.1` for now but if I get time this evening I may try and dig a bit deeper and see whats happening in `1.2.1` to cause this.

**Comment by kylef** [comment]
I've figured out the problem. Please upgrade to version 1.2.2 which has a fix.
