### ISSUE TITLE
Simulate delay of responses

### ISSUE THREAD

**Issue by alessandroorru** [kylef/Mockingjay#52]
Is there any builtin functionality to add a delay to the responses, in order to simulate a real server hit? 

I find it really useful for both automated UI tests and during development, in case I want to check the "loading" status with a controlled response.

**Comment by kylef** [comment]
There isn't any way to do this yet. My own use of Mockingjay is for unit test and haven't added these sort of features.

I think it would be pretty easy to add. We could add a delay time to the `Stub` structure itself, and then `MockingjayProtocol` can add the delay after matching the stub to creating the builder.

**Comment by kylef** [comment]
If anyone is interested in contributing support for delays I think it would be a great first time contributor task. It should be added relatively easy to implement.

- We can add a delay property to [`Stub`](https://github.com/kylef/Mockingjay/blob/2dd1ff3fb3ed30ed422ed6c9f8d095d67dbfcfd5/Mockingjay/MockingjayProtocol.swift#L13) (`let delay: TimeInterval?`)
- Expose an optional delay time interval on the [XCTest `stub` helper](https://github.com/kylef/Mockingjay/blob/https://github.com/kylef/Mockingjay/blob/master/Mockingjay/XCTest.swift#L34/Mockingjay/XCTest.swift#L34)
- During [`startLoading`](https://github.com/kylef/Mockingjay/blob/master/Mockingjay/MockingjayProtocol.swift#L88), we should check the stub for a `delay` interval. If set, then delay (perhaps using `NSTimer`) most of the work during `startLoading`.
