### ISSUE TITLE
Add support for Swift 3/Xcode 8

### ISSUE THREAD

**Issue by adamdebono** [kylef/Mockingjay#55]
I've attempted to convert the project over using the Xcode 8 refactor tool, and fixed a few things manually. I am having trouble with the `MockingjayAsyncProtocolTests`. Those tests will show a number 2-second timeout messages, and then just seems to sit there and not won't complete the test. All of the other tests pass fine.

My code is on my fork, adamdebono/Mockingjay@bfc0e718119dd8366637b1e7321f51d10274743d

(Also I have pointed URITemplate to my own fork which has also been updated to Swift 3 as well)

**Comment by AnthonyMDev** [comment]
@kylef I know you're probably very busy, but is there any chance we can get a this done soon?

Thanks!

**Comment by garnett** [comment]
Any update on this?

**Comment by kylef** [comment]
Release [2.0.0](https://github.com/kylef/Mockingjay/releases/tag/2.0.0) which has Swift 3 support.
