### ISSUE TITLE
Turn ENABLE_BITCODE = YES for watchOS result in compilation errors.

### ISSUE THREAD

**Issue by bluebeans** [kylef/Mockingjay#57]
In mockingjay.xcconfig, turn ENABLE_BITCODE = YES. Turn bitcode on for all the other targets in the project too. This is required for watchOS. Please resolve this because it is a show stopper for us.

Get compilation error: 

ld: '/Users/nyan/Library/Developer/Xcode/DerivedData/zipcar-bjuclsirfazpdbhbekejanyrfonv/Build/Products/Debug-iphoneos/Mockingjay/Mockingjay.framework/Mockingjay' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kylef** [comment]
@bluebeans Would you like to submit a pull request enabling this flag?

**Comment by borut-t** [comment]
@kylef any special reason why bitcode is disabled in the first place?

**Comment by teameh** [comment]
I've got the same problem (on v2.0.1). Was this fixed or was the issue just closed?

**Comment by yfujiki** [comment]
@kylef I second to @borut-t. What is the reason that bitcode is disabled? 

It hinders our development experience when we want to mock data at actual runtime (not test) to show sneak peek build for our testers/designers. 

I think at least it should be noted at README. that "you cannot use Mockingjay to mock data at runtime when the project has `ENABLE_BITCODE=true`)"
