### ISSUE TITLE
How I can mock a download image

### ISSUE THREAD

**Issue by RafaelPlantard** [kylef/Mockingjay#59]
I want to mock this download http://polishop.vteximg.com.br/arquivos/ids/404438_2 that I'm using AlamofireImage.
Can you help me?

**Comment by jmburges** [comment]
hey @RafaelPlantard the `http` builder has an `NSData` argument to it. I haven't tested this, but something like this should work

```swift
let imageData: NSData = UIImagePNGRepresentation(myImage)
let imageURL= "http://polishop.vteximg.com.br/arquivos/ids/404438_2"
stub(uri(imageURL), builder: http(200, headers: nil, data: imageData))
```
