### ISSUE TITLE
Can I mock language headers?

### ISSUE THREAD

**Issue by Ricardo1980** [kylef/Mockingjay#60]
Can I use this lib mock "Accept-Language" with "en-US;q=1.0" value rather than the system (iphone or MAC) value? 
Thanks a lot.

**Comment by kylef** [comment]
I'm not too sure what you are asking, but it doesn't seem to have any relevance to this library since this library is not responsible for creating requests.

I think all you are looking to do is set the `Accept-Language` header on a request? If so, you can just set this on your request:

```swift
let request = NSMutableURLRequest(URL: myURL)
request.setValue("en-US;q=1.0", forHTTPHeaderField: "Accept-Language")
```

**Comment by Ricardo1980** [comment]
Finally I could stub NSLocale.preferredLanguages in Swift, so my tests are working.
Code here:
http://stackoverflow.com/questions/38919827/how-can-i-mock-nslocale-preferredlanguages-in-swift-to-test-requests/38951886#38951886
