### ISSUE TITLE
Cannot stub with Mockingjay 1.3.0

### ISSUE THREAD

**Issue by banjun** [kylef/Mockingjay#68]
https://github.com/CocoaPods/Specs/commit/09a78b7e04629faf7e753e295ea3789ab5126772
seems to omit `Mockingjay/MockingjayURLSessionConfiguration.m`.
related to #51

**Comment by banjun** [comment]
possibly this can be closed by #66 and #67

**Comment by kylef** [comment]
This should be fixed in the 1.3.1 release. let me know if you have any problems.
