### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ehuynh** [kylef/Mockingjay#69]
I'm just wondering if this project is open to putting official support for `Carthage`. Perviously it was possible to get `Mockingjay` (**sort of**) working with `Carthage` just by adding both `Mockingjay` and `URITemplate` to the `Cartfile`.

But moving to Swift 3 support and this no longer works. 

One of the reasons is that `URITemplate` has now removed the Xcode project file for the repo which `Carthage` relies on to build the framework. This means that if we are going to add Carthage support for this, we will probably need to restore the project file in the `URITemplate` repo.

The other issue is that, as I mentioned above, the previous method only **sort of** worked. I'm not 100% sure on this, but because this repo includes URITemplate as a submodule, when `Carthage` checkouts/clones this repo as a dependency, it also checkouts the `URITemplate` submodule. So I think that when the project is built, it is using the commit/version of `URITemplate` that the submodule points to. Then when used in our test target, it uses a different version of `URITemplate` framework which is built using the commit/version that is resolved by `Carthage` (which might no necessarily be the same as the one that is pointed to by the `URITemplate` submodule in this repo).

TBH, I'm not necessarily sure what the best way is to resolve the issue above. A solution might involve changing the location of the `URITemplate` project to the `Carthage/Checkout/URITemplate` path, and using `Carthage` to checkout the dependencies before building the project in Xcode. 

Thoughts?

**Comment by callo90** [comment]
updates about this?

**Comment by kylef** [comment]
I do not intend to add this, if you're looking for similar functionality [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs) provides almost an identical API and supports Carthage.
