### ISSUE TITLE
URI Template not updated to Swift 3

### ISSUE THREAD

**Issue by baoskee** [kylef/Mockingjay#73]
Hi, it looks like the Pod URITemplate dependency is making Mockingjay failing with Swift 3.

**Comment by kylef** [comment]
Could you please elaborate on what problem you are having? Perhaps including some steps to reproduce?

**Comment by baoskee** [comment]
Yes! 
* Include pod 'Mockingjay' in your test target, and run pod install
* In your test files, import Mockingjay
* Build and URI Template will have a lot of build errors since it has not migrated to Swift 3.

And do this using Xcode8. My pod install message says I installed Mockingjay (1.3.1) and URITemplate (1.4.0).

**Comment by kylef** [comment]
Mockingly 1.3.1 doesn't support Swift 3. You will need to use [Mockingjay 2.0.0](https://github.com/kylef/Mockingjay/releases/tag/2.0.0) for Swift support.

**Comment by baoskee** [comment]
Got it. I had to use "pod repo update" and then "gem install cocoapods --pre" since pod install Mockingjay ~>2.0.0 gets a not found error. Thanks.
