### ISSUE TITLE
Empty Body

### ISSUE THREAD

**Issue by cs-joao-souza** [kylef/Mockingjay#84]
How can i stub a request with only status code? Without body.

I've been trying to do that but with no success.

I did this

stub(http(method.toMockingjay(), uri: endpointPath), http(401))

And a do need to get the statusCode but the DataResponse.response from Alamofire is always nil

**Comment by ntokozotep** [comment]
Try this
```
let response = http(401, headers: nil, download: nil)
stub(http(method.toMockingjay(), uri: endpointPath), response)
```

**Comment by cs-joao-souza** [comment]
Thanks. It worked.
