### ISSUE TITLE
Swift 4 Support - Podspec update

### ISSUE THREAD

**Issue by jameswwwebster** [kylef/Mockingjay#87]
I see the changes for Swift 4 have been made. However, the pod spec hasn't been updated so this refactor remains unavailable on Cocoapods.

**Comment by ptseng** [comment]
https://github.com/kylef/Mockingjay/pull/88

**Comment by rwgrier** [comment]
@kylef Can we get this taken care of? I see you've made Swift 4 changes in `master` can we get a new release? @ptseng even made a PR of the podspec for you (#88). 

We've got Swift 4 projects and would like to use this in our unit testing target, but can't yet.

**Comment by ptseng** [comment]
@kylef Thanks for the update.
