### ISSUE TITLE
Proposal for callback for matcher

### ISSUE THREAD

**Issue by icanswiftabit** [kylef/Mockingjay#89]
I was thinking what would help me in testing. Callback when stub responds to request. 
I am more than happy to implement it. 
What do you think @kylef ?

**Comment by kylef** [comment]
Both the matcher and builder are already callbacks, you are free to put whatever logic you want in those places. The "builder" is invoked when the stub is matched.

```swift
stub(http(.post, uri: "https://example.com/authorisations")) { request in
  XCTAssertEqual(request.allHTTPHeaderFields?["Authorization"], "Bearer abc123")
  XCTAssertEqual(request.allHTTPHeaderFields?["Content-Type"], "application/json")

  if denied {
    return json(["token": "newtokenabc"])(request)
  }

  denied = true
  return problem(code: 403, title: "Access Denied")(request)
}
```
